### ISSUE TITLE
请问algmon-llm-wechat-template这个项目在接入dify（本地化部署）时报错

### ISSUE THREAD

**Issue by mengdahuang** [weijiang2023/algmon-llm-wechat-jiang#2]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

terminal

### 问题描述 😯

哈喽大佬，

我看到您在chatgpt-on-wechat这个项目里提了个PR，然后关注到您https://github.com/weijiang2023/algmon-llm-wechat-template 这个项目。我将该项目拉取到本地并配置dify相关配置:
'use_difyai': True, 'difyai_api_key': 'app-2vg23BQcqn5qXoaX0VQAN1p9', 'difyai_api_base': 'http://172.16.33.61/v1'
并启用机器人后无法回复消息，报错如下：
![image](https://github.com/weijiang2023/algmon-llm-wechat-jiang/assets/32334062/66127b36-796a-4c88-802c-a72a841db81c)

可否麻烦大佬指点下？从日志看，好像把我的请求指向dify.ai 云端的API去了，怎样改为本地的API？
多谢！

### 终端日志 📒

```log
[INFO][2023-09-05 12:09:06][chatgpt.py:186] - proxy no find, directly request to chatgpt instead
[INFO][2023-09-05 12:09:06][victorinox.py:86] - use_tools=['python', 'terminal', 'meteo-weather', 'url-get'], params: {'debug': False, 'openai_api_key': 'sk-Uxxxxxx4D0', 'open_ai_api_base': 'https://api.xxxxx.com/v1', 'deployment_id': '', 'proxy': '', 'request_timeout': 600, 'model_name': 'gpt-3.5-turbo-16k', 'no_default': False, 'top_k_results': 3, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', 'google_cse_id': '', 'searx_search_host': '', 'wolfram_alpha_appid': '', 'morning_news_api_key': '', 'cuda_device': 'cpu', 'think_depth': 3, 'arxiv_summary': True, 'morning_news_use_llm': False, 'llm_api_key': 'sk-UoFr8VREuq4lxxxxxx', 'llm_api_base_url': 'https://api.xxxx.com/v1'}
[INFO][2023-09-05 12:09:06][tool.py:31] - [tool] inited
[INFO][2023-09-05 12:09:06][role.py:69] - [Role] inited
[INFO][2023-09-05 12:09:06][linkai.py:23] - [LinkAI] inited
[INFO][2023-09-05 12:09:06][dungeon.py:56] - [Dungeon] inited
[INFO][2023-09-05 12:09:06][hello.py:23] - [Hello] inited
[INFO][2023-09-05 12:09:06][finish.py:23] - [Finish] inited
[INFO][2023-09-05 12:09:09][wechat_channel.py:126] - Wechat login success, user_id: @d65cd7c395293d4a4727fd9f76717200410b9487fxxxx, nickname: 小黄同学
/home/jason/.pyenv/versions/wechat-GPTbot/lib/python3.8/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Start auto replying.
[INFO][2023-09-05 12:09:30][bridge.py:40] - create bot difyai for chat
[INFO][2023-09-05 12:09:30][dify_ai_bot.py:66] - [DIFYAI] query=hi
[ERROR][2023-09-05 12:09:31][dify_ai_bot.py:79] - 401 Client Error: Unauthorized for url: https://api.dify.ai/v1/chat-messages
Traceback (most recent call last):
  File "/home/jason/app/chatgpt-on-wechat-supportdify/bot/difyai/dify_ai_bot.py", line 69, in _chat
    chat_response.raise_for_status()
  File "/home/jason/.pyenv/versions/wechat-GPTbot/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.dify.ai/v1/chat-messages
[WARNING][2023-09-05 12:09:33][dify_ai_bot.py:82] - [DIFYAI] do retry, times=0
[INFO][2023-09-05 12:09:33][dify_ai_bot.py:66] - [DIFYAI] query=hi
[ERROR][2023-09-05 12:09:34][dify_ai_bot.py:79] - 401 Client Error: Unauthorized for url: https://api.dify.ai/v1/chat-messages
Traceback (most recent call last):
  File "/home/jason/app/chatgpt-on-wechat-supportdify/bot/difyai/dify_ai_bot.py", line 69, in _chat
    chat_response.raise_for_status()
  File "/home/jason/.pyenv/versions/wechat-GPTbot/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.dify.ai/v1/chat-messages

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/app/chatgpt-on-wechat-supportdify/bot/difyai/dify_ai_bot.py", line 69, in _chat
    chat_response.raise_for_status()
  File "/home/jason/.pyenv/versions/wechat-GPTbot/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.dify.ai/v1/chat-messages
[WARNING][2023-09-05 12:09:36][dify_ai_bot.py:82] - [DIFYAI] do retry, times=1
[WARNING][2023-09-05 12:09:36][dify_ai_bot.py:53] - [DIFYAI] failed after maximum number of retry times
[INFO][2023-09-05 12:09:37][wechat_channel.py:189] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
请再问我一次吧), receiver=@312e4c6b7cdec
```

**Comment by mengdahuang** [comment]
close
